apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: zuri-market
spec:
  replicas: 2
  strategy:
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      serviceAccountName: backend-sa
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: ghcr.io/dammy123-ai/capstone-project-04-backend:latest
          ports:
            - name: http
              containerPort: 5050
          envFrom:
            - configMapRef: { name: backend-config }
            - secretRef: { name: backend-secrets }
          readinessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 192Mi }
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }