apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: zuri-market
data:
  default.conf: |
    server {
      listen 8080;
      root /usr/share/nginx/html;
      index index.html;
      location / { try_files $uri /index.html; }
    }